# Generated by Django 5.0.6 on 2024-06-07 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_artistgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtistGroup',
            new_name='SongShareUserGroup',
        ),
    ]
