# Generated by Django 5.0.6 on 2024-06-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('seats', models.IntegerField(default=0)),
                ('event_date', models.DateField()),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
