# Generated by Django 5.0.6 on 2024-06-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('soundcloud_url', models.CharField(blank=True, default='', max_length=256)),
                ('favorites', models.IntegerField(default=0)),
            ],
        ),
    ]
